### Data endpoint 
GET http://localhost:8080/api/data

### Add new user
POST http://localhost:8080/api/data
Content-Type: application/json

{
    "name" : "bot2"
}

### DELETE END POINT

DELETE http://localhost:8080/api/data