### READ
GET http://localhost:8080/api/data

### CREATE
POST http://localhost:8080/api/data
Content-Type: application/json

{
  "name": "bot3"
}

### UPDATE
PUT http://localhost:8080/api/data/3
Content-Type: application/json

{
  "name": "botX"
}

### DELETE
DELETE http://localhost:8080/api/data/3
